# Generated by Django 4.0.3 on 2022-04-03 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctor_receptionist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Gender',
            new_name='gender',
        ),
    ]
